import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./index.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Supplier Management",
//   description: "Generated by create next app",
// };

// ===============================
// SEO METADATA
// ===============================
export const metadata: Metadata = {
  title: {
    default: "Supplier-Management",
    template: "%s | My Website",
  },
  description:
    "My Website offers high-quality products, best services, and amazing deals. Trusted by thousands of customers worldwide.",
  keywords: [
    "ecommerce",
    "online store",
    "best products",
    "shopping",
    "react",
    "next js",
  ],
  authors: [{ name: "Bishwajit Sarkar" }],
  creator: "Bishwajit Sarkar",
  publisher: "My Website",
  metadataBase: new URL("https://www.mywebsite.com"),

  // Open Graph (FB, LinkedIn)
  openGraph: {
    title: "My Website – Best Products & Services",
    description:
      "Shop premium products with fast delivery and 24/7 support.",
    url: "https://www.mywebsite.com",
    siteName: "My Website",
    images: [
      {
        url: "/seo/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "My Website Open Graph Image",
      },
    ],
    locale: "en_US",
    type: "website",
  },

  // Twitter Card (X)
  twitter: {
    card: "summary_large_image",
    title: "My Website – Best Products & Services",
    description: "Shop premium products with fast delivery.",
    images: ["/seo/twitter-image.jpg"],
    creator: "@mywebsite",
  },

  // Robots (SEO)
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  // Canonical URL
  alternates: {
    canonical: "https://www.mywebsite.com",
  },

  // Icons
  icons: {
    icon: "/favicon.svg",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
